# Generated by Django 5.2.12 on 2026-08-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'ผู้ดูแลระบบ',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faq_id', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'คำถามที่พบบ่อย',
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('category_id', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='plant_categories', to='PlantAI_App.admin')),
            ],
            options={
                'verbose_name': 'หมวดหมู่พืช',
                'db_table': 'plant_category',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=50)),
                ('light', models.CharField(max_length=10)),
                ('water', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='PlantAI_App.admin')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='PlantAI_App.plantcategory')),
            ],
            options={
                'verbose_name': 'พืช',
                'db_table': 'plant',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('log_id', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('filter_light', models.CharField(blank=True, max_length=10, null=True)),
                ('filter_water', models.CharField(blank=True, max_length=10, null=True)),
                ('filter_humidity', models.CharField(blank=True, max_length=10, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='PlantAI_App.plantcategory')),
            ],
            options={
                'verbose_name': 'ประวัติการค้นหา',
                'db_table': 'search_log',
            },
        ),
        migrations.CreateModel(
            name='SearchSummary',
            fields=[
                ('summary_id', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('filter_light', models.CharField(blank=True, max_length=10, null=True)),
                ('filter_water', models.CharField(blank=True, max_length=10, null=True)),
                ('filter_humidity', models.CharField(blank=True, max_length=10, null=True)),
                ('search_count', models.IntegerField(default=0)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_summaries', to='PlantAI_App.plantcategory')),
                ('faq', models.ForeignKey(blank=True, db_column='faq_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_summaries', to='PlantAI_App.faq')),
            ],
            options={
                'verbose_name': 'สรุปผลการค้นหา',
                'db_table': 'search_summary',
            },
        ),
    ]
