# Generated by Django 5.2.12 on 2026-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantAI_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='humidity',
            field=models.CharField(choices=[('low', 'ความชื้นต่ำ'), ('medium', 'ความชื้นปานกลาง'), ('high', 'ความชื้นสูง')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light',
            field=models.CharField(choices=[('low', 'แสงน้อย / รำไร'), ('medium', 'แสงปานกลาง'), ('high', 'แสงมาก / แดดจัด')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water',
            field=models.CharField(choices=[('low', 'น้ำน้อย'), ('medium', 'น้ำปานกลาง'), ('high', 'น้ำมาก')], max_length=20),
        ),
    ]
