# Generated by Django 5.2.12 on 2026-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantAI_App', '0003_alter_plant_humidity_alter_plant_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='light',
            field=models.CharField(choices=[('low', 'แสงน้อย'), ('medium', 'แสงปานกลาง'), ('high', 'แสงมาก')], max_length=10),
        ),
    ]
