# Generated by Django 5.2.12 on 2026-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantAI_App', '0004_alter_plant_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plantcategory',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
